import XCTest
@testable import CodeBerry

/// 4.0.3 S10 (P0-H): generated source isolation.
///
/// A generated fixture must never become a second production view and
/// must never shadow a production symbol of the same name.
final class GeneratedSourceIsolationTests: XCTestCase {

    // MARK: - Role classification

    func testRoleClassification() {
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/HomeView.swift"), .production)
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/Features/Home/HomeView.swift"), .production)
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/PreviewFixtures/HomeViewFixture.swift"),
                       .generatedFixture)
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/HomeViewFixture.swift"),
                       .generatedFixture)
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/Some.swift",
                                                  content: "// generated by CodeBerry 4.0\nstruct X: View {}"),
                       .generatedFixture)
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/PreviewFixtures/V36Acceptance/HomeView.swift"),
                       .acceptanceFixture)
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/HomeTests.swift"), .test)
        XCTAssertEqual(PreviewSourceRole.classify(path: "Proj/Tests/HomeTests.swift"), .test)

        XCTAssertTrue(PreviewSourceRole.production.isPreviewablePage)
        XCTAssertFalse(PreviewSourceRole.generatedFixture.isPreviewablePage)
        XCTAssertFalse(PreviewSourceRole.acceptanceFixture.isPreviewablePage)
        XCTAssertFalse(PreviewSourceRole.test.isPreviewablePage)
    }

    // MARK: - Index: production wins

    /// A generated file defining the same view name loses to production,
    /// with a diagGeneratedShadowed warning.
    func testProductionShadowsGenerated() throws {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("CB403Isolation-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }

        let prod = """
            import SwiftUI
            struct HomeView: View {
                var body: some View { Text("PROD") }
            }
            """
        // The old header+source fixture path: same struct name, generated.
        let fixture = """
            // Preview Fixture — generated by CodeBerry 4.0 (M3)
            // Source: HomeView.swift

            import SwiftUI
            struct HomeView: View {
                var body: some View { Text("FIXTURE") }
            }
            """
        try prod.write(to: root.appendingPathComponent("HomeView.swift"),
                       atomically: true, encoding: .utf8)
        let fixtureDir = root.appendingPathComponent("PreviewFixtures")
        try FileManager.default.createDirectory(at: fixtureDir, withIntermediateDirectories: true)
        try fixture.write(to: fixtureDir.appendingPathComponent("HomeViewFixture.swift"),
                          atomically: true, encoding: .utf8)

        let index = PreviewProjectIndex()
        index.update(projectRoot: root, projectName: "Proj",
                     currentPath: "Proj/HomeView.swift", currentSource: prod,
                     readFile: { path in
                        let rel = path.hasPrefix("Proj/")
                            ? String(path.dropFirst("Proj/".count)) : path
                        return try? String(contentsOf: root.appendingPathComponent(rel),
                                            encoding: .utf8)
                     })

        // Production wins regardless of file order.
        let winner = try XCTUnwrap(index.viewsByName["HomeView"])
        XCTAssertTrue(winner.file.hasSuffix("HomeView.swift"))
        XCTAssertFalse(winner.file.contains("PreviewFixtures"),
                       "generated fixture must not shadow production: \(winner.file)")

        // The collision is observable, with the specific key.
        XCTAssertTrue(index.indexDiagnostics.contains { $0.key == .diagGeneratedShadowed },
                      "\(index.indexDiagnostics.map(\.message))")
    }

    // MARK: - Page Discovery: no second production view

    /// A generated `HomeViewFixture` never appears in the previewable
    /// (page discovery) list.
    func testFixtureNotAPreviewablePage() throws {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("CB403Pages-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }

        try """
            import SwiftUI
            struct HomeView: View {
                var body: some View { Text("PROD") }
            }
            """.write(to: root.appendingPathComponent("HomeView.swift"),
                      atomically: true, encoding: .utf8)
        let fixtureDir = root.appendingPathComponent("PreviewFixtures")
        try FileManager.default.createDirectory(at: fixtureDir, withIntermediateDirectories: true)
        try """
            // Preview Fixture — generated by CodeBerry 4.0 (M3)
            import SwiftUI
            struct HomeViewFixture: View {
                var body: some View { Text("FIXTURE") }
            }
            """.write(to: fixtureDir.appendingPathComponent("HomeViewFixture.swift"),
                      atomically: true, encoding: .utf8)

        let analysis = ProjectAnalyzer.analyze(root: root)
        let names = analysis.candidates.map(\.viewName)
        XCTAssertTrue(names.contains("HomeView"), "\(names)")
        XCTAssertFalse(names.contains("HomeViewFixture"),
                       "generated fixture must not be a previewable page: \(names)")
    }
}
