import Foundation

/// 4.0.3 S10 (P0-H): source-role policy — generated sources are isolated
/// from production.
///
/// A generated fixture (e.g. `PreviewFixtures/HomeViewFixture.swift`)
/// must never become a second production view, and must never shadow a
/// production symbol of the same name. Roles:
/// - production: hand-written project source.
/// - generatedFixture: files CodeBerry generated (`PreviewFixtures/`,
///   `*Fixture.swift`, or the "generated by CodeBerry" header).
/// - acceptanceFixture: the V36 acceptance corpus (test-only, never a
///   user project file).
/// - test: `*Tests.swift` / `*/Tests/*`.
/// - debugPrototype: scratch/prototype files.
///
/// Enforcement:
/// - Page Discovery / the previewable list only include production
///   (`isPreviewablePage`).
/// - `PreviewProjectIndex.rebuildLookup`: a production definition always
///   wins over a same-name generated/test/prototype definition, with a
///   `diagGeneratedShadowed` warning.
enum PreviewSourceRole: String, Sendable {
    case production
    case generatedFixture
    case acceptanceFixture
    case test
    case debugPrototype

    /// Classify a project-relative path, optionally with file content
    /// (the content check catches fixtures kept outside PreviewFixtures/).
    static func classify(path: String, content: String? = nil) -> PreviewSourceRole {
        let lower = path.lowercased()
        let fileName = (path as NSString).lastPathComponent
        // The acceptance corpus also lives under PreviewFixtures/ —
        // check it first.
        if lower.contains("v36acceptance") { return .acceptanceFixture }
        if lower.contains("previewfixtures/") { return .generatedFixture }
        if fileName.hasSuffix("Fixture.swift") { return .generatedFixture }
        if let content, content.contains("generated by CodeBerry") { return .generatedFixture }
        if lower.contains("/tests/") || fileName.hasSuffix("Tests.swift")
            || fileName.hasSuffix("Test.swift") { return .test }
        if lower.contains("preview content/") || fileName.contains("Prototype")
            || fileName.contains("Scratch") { return .debugPrototype }
        return .production
    }

    /// Only production views appear in Page Discovery / the previewable list.
    var isPreviewablePage: Bool { self == .production }
}
