import Foundation
import SwiftParser
import SwiftSyntax

// MARK: - 4.0.2 P0-7: preview-only SwiftData-bypassing fixture wrapper
//
// The old "fixture" was a verbatim source snapshot: opening it in Xcode
// Previews ran the view against the REAL SwiftData store (or failed without
// a container). This generator instead emits a preview-only WRAPPER
// (`<View>PreviewFixture`) that truly bypasses SwiftData:
//
//   - Production logic / schema / Repository are never modified — the
//     generator only READS the view's source (it returns a String).
//   - The wrapper injects an IN-MEMORY ModelContainer built from the `@Query`
//     element types discovered in the source: no real DB writes, ever.
//   - The wrapper performs no network I/O.
//
// The CodeBerry canvas itself never executes SwiftData at all (P0-6 mocks);
// this wrapper targets Xcode `#Preview`.

struct PreviewFixtureGenerator {
    struct FixturePlan: Sendable {
        /// e.g. "HomeViewPreviewFixture"
        let wrapperName: String
        /// The wrapped view, e.g. "HomeView"
        let viewName: String
        /// `@Query` element types discovered in the view's source.
        let modelTypes: [String]
        /// Full file source of `<View>PreviewFixture.swift`.
        let source: String
    }

    /// Build a fixture plan for `viewName` from its source.
    /// Returns nil when the source doesn't define that view, has syntax
    /// errors, or the view doesn't use SwiftData (no wrapper needed).
    static func plan(for viewName: String, in source: String) -> FixturePlan? {
        let tree = Parser.parse(source: source)
        guard !tree.hasError else { return nil }
        let finder = QueryFinder(viewName: viewName)
        finder.walk(tree)
        guard finder.foundView, finder.usesSwiftData else { return nil }

        let wrapperName = "\(viewName)PreviewFixture"
        let models = finder.modelTypes
        let containerArgs = models.isEmpty
            ? "for: []"
            : "for: [\(models.map { "\($0).self" }.joined(separator: ", "))]"
        let modelNote = models.isEmpty
            ? "\n// No @Query models were discovered in \(viewName); add your @Model\n// types to the `for:` list below if the preview needs them."
            : ""

        let fileSource = """
        // \(wrapperName).swift
        // Preview-only fixture — generated by CodeBerry 4.0.2 (P0-7).
        //
        // SwiftData is truly bypassed: the wrapper injects an IN-MEMORY
        // container, so Xcode Previews never touch the real database and no
        // network calls are made. Production logic, schema, and Repository
        // code are untouched — this file only references \(viewName).
        // DO NOT SHIP — preview only.
        \(modelNote)
        import SwiftUI
        import SwiftData

        /// Preview-only wrapper for `\(viewName)`.
        struct \(wrapperName): View {
            var body: some View {
                \(viewName)()
                    .modelContainer(\(containerArgs), inMemory: true)
            }
        }

        #Preview("\(viewName) — Fixture (in-memory SwiftData)") {
            \(wrapperName)()
        }
        """
        return FixturePlan(wrapperName: wrapperName, viewName: viewName,
                           modelTypes: models, source: fileSource)
    }

    // MARK: - Syntax walk

    private final class QueryFinder: SyntaxVisitor {
        let viewName: String
        var foundView = false
        var usesSwiftData = false
        var modelTypes: [String] = []
        private var insideTargetView = false
        // 4.0.2: a stack, not a defer — SyntaxVisitor visits children
        // AFTER visit() returns, so `defer { insideTargetView = was }`
        // would reset the flag before the @Query vars are ever seen
        // (that bug silently produced modelTypes == []).
        private var viewStack: [Bool] = []

        init(viewName: String) {
            self.viewName = viewName
            super.init(viewMode: .sourceAccurate)
        }

        override func visit(_ node: ImportDeclSyntax) -> SyntaxVisitorContinueKind {
            if node.path.map(\.name.text).joined(separator: ".") == "SwiftData" {
                usesSwiftData = true
            }
            return .skipChildren
        }

        override func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind {
            let inherits = (node.inheritanceClause?.inheritedTypes ?? []).map { $0.type.trimmedDescription }
            let isTarget = node.name.text == viewName && inherits.contains("View")
            if isTarget { foundView = true }
            viewStack.append(isTarget)
            insideTargetView = viewStack.contains(true)
            return .visitChildren
        }

        override func visitPost(_ node: StructDeclSyntax) {
            if !viewStack.isEmpty { viewStack.removeLast() }
            insideTargetView = viewStack.contains(true)
        }

        override func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
            let isQuery = node.attributes.contains { element in
                if case .attribute(let attr) = element {
                    return attr.attributeName.trimmedDescription == "Query"
                }
                return false
            }
            if isQuery {
                usesSwiftData = true
                if insideTargetView {
                    for binding in node.bindings {
                        let typeDesc = binding.typeAnnotation?.type.trimmedDescription ?? ""
                        if let element = MockCenter.arrayElementType(of: typeDesc),
                           !modelTypes.contains(element) {
                            modelTypes.append(element)
                        }
                    }
                }
            }
            return .visitChildren
        }

        override func visit(_ node: DeclReferenceExprSyntax) -> SyntaxVisitorContinueKind {
            let name = node.baseName.text
            if name == "modelContext" || name == "ModelContext" || name == "ModelContainer" {
                usesSwiftData = true
            }
            return .skipChildren
        }
    }
}
